import json

def generate_markdown_report(data, resource_id, current_type):
    # Parse the JSON string coming from Claude
    recommendation = json.loads(data)
    
    report = f"""
# 📉 FinOps Audit Report: {resource_id}

## Summary
| Metric | Value |
| :--- | :--- |
| **Current Instance** | `{current_type}` |
| **Recommended Instance** | `{recommendation['recommendation']}` |
| **Est. Monthly Savings** | `{recommendation['estimated_savings_pct']}` |

## Analysis & Justification
{recommendation['justification']}

## Required Action
Update the `instance_type` variable in `terraform/modules/main.tf` to `{recommendation['recommendation']}`.

---
*Generated by Autonomous FinOps Auditor (Claude 4.6 Sonnet)*
"""
    with open("remediation_report.md", "w") as f:
        f.write(report)
    print("🚀 Markdown report generated: remediation_report.md")

# Run it!
if __name__ == "__main__":
    # Use the result you just got from your previous run
    raw_ai_json = """{
        "recommendation": "t3.medium",
        "justification": "With only 0.09% average CPU utilization, this workload is severely over-provisioned...",
        "estimated_savings_pct": "85%"
    }"""
    generate_markdown_report(raw_ai_json, "i-02dc32ab8ac15dda7", "m5.xlarge")